CREATE TABLE IF NOT EXISTS Region (
    NOC CHAR(3) PRIMARY KEY,
    Region VARCHAR(100),
    Notes VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Athlete (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Sex CHAR(1),
    Age FLOAT,
    Height FLOAT,
    Weight FLOAT,
    NOC CHAR(3) NOT NULL,
    FOREIGN KEY (NOC) REFERENCES Region(NOC)
);

CREATE TABLE IF NOT EXISTS Event (
    e_id SERIAL PRIMARY KEY,
    Event VARCHAR(200) NOT NULL,
    Sport VARCHAR(100) NOT NULL,
    City VARCHAR(100) NOT NULL,
    Season VARCHAR(10) NOT NULL,
    Year INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Athlete_Event (
    ID INT,
    e_id INT,
    Medal VARCHAR(20),
    PRIMARY KEY (ID, e_id),
    FOREIGN KEY (ID) REFERENCES Athlete(ID),
    FOREIGN KEY (e_id) REFERENCES Event(e_id)
);

CREATE TABLE IF NOT EXISTS Team (
    T_Id SERIAL PRIMARY KEY,
    NOC CHAR(3) NOT NULL,
    Team VARCHAR(100) NOT NULL,
    FOREIGN KEY (NOC) REFERENCES Region(NOC)
);

CREATE TABLE IF NOT EXISTS Athlete_Team (
    ID INT,
    T_Id INT,
    PRIMARY KEY (ID, T_Id),
    FOREIGN KEY (ID) REFERENCES Athlete(ID),
    FOREIGN KEY (T_Id) REFERENCES Team(T_Id)
);

CREATE TABLE IF NOT EXISTS Athlete_Region (
    ID INT,
    NOC CHAR(3),
    PRIMARY KEY (ID, NOC),
    FOREIGN KEY (ID) REFERENCES Athlete(ID),
    FOREIGN KEY (NOC) REFERENCES Region(NOC)
);